package com.brook.blooddonor;

import jakarta.validation.Valid;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

@Controller
public class BloodDonorController {

    @GetMapping
    public String showDonorForm(Model model) {
        // Create an empty Donor object so the form can bind to its fields
        model.addAttribute("donor", new Donor());
        // Load the donor_form.mustache template
        return "donor_form";
    }

    @PostMapping("/submitDonorForm")
    public String processDonorForm(@Valid Donor donor, BindingResult bindingResult, Model model) {

        // If validation annotations on Donor.java failed
        if (bindingResult.hasFieldErrors()) {

            // Collect all validation errors generated by @Valid
            List<FieldError> fieldErrors = bindingResult.getFieldErrors();

            // Convert the list of FieldError objects into a simple Map
            // key = field name, value = error message
            Map<String, String> validationErrorMap = ErrorUtils.createErrorMap(fieldErrors);

            // Add the map to the model so the form can display the messages
            model.addAttribute("validationErrorMap", validationErrorMap);

            // Go back to the form so the user can fix their mistakes
            return "donor_form";

        } else {
            // No validation errors, now apply rules

            String resultMessage;
            List<String> ineligibleReasons = new ArrayList<>();

            // Check the age requirement
            if (donor.getAge() < 16) {
                ineligibleReasons.add("Age must be at least 16");
            }

            // Check the weight requirement
            if (donor.getWeight() < 110) {
                ineligibleReasons.add("Weight must be at least 110lbs");
            }

            // If no ineligible reasons, the donor passes the rules
            if (ineligibleReasons.isEmpty()) {
                resultMessage = "you may be eligible to donate blood";

            } else {
                // Donor failed one or more requirements
                resultMessage = "You are NOT eligible to donate blood";

                // Send the list of reasons to the results page
                model.addAttribute("ineligibleReasons", ineligibleReasons);
            }

            // Add the final eligibility message
            model.addAttribute("resultMessage", resultMessage);

            // Load results.mustache (the result page)
            return "results";
        }
    }

}







